# Generated by Django 2.2.6 on 2019-11-08 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_mymodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
