# Generated by Django 2.2.6 on 2019-11-10 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0010_remove_blog_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='bid',
            field=models.CharField(default='', max_length=200),
        ),
    ]
