# Generated by Django 2.2.6 on 2019-11-10 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0011_blog_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='img',
            field=models.ImageField(default='', upload_to='media'),
        ),
    ]
