# Generated by Django 2.2.6 on 2019-11-10 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0017_auto_20191110_0607'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='fileflag',
            field=models.BooleanField(default=False),
        ),
    ]
