# Generated by Django 2.2.6 on 2019-10-28 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(max_length=50),
        ),
    ]
