# Generated by Django 2.2.6 on 2019-11-03 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_userdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata',
            old_name='usercat',
            new_name='ucategory',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='uid',
        ),
        migrations.AddField(
            model_name='userdata',
            name='uemail',
            field=models.CharField(default='', max_length=100),
        ),
    ]
