# Generated by Django 2.2.6 on 2019-11-10 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0016_auto_20191110_0537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='img',
            field=models.ImageField(blank=True, default='', null=True, upload_to='post_images'),
        ),
    ]
