# Generated by Django 2.2.6 on 2019-11-10 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0018_blog_fileflag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='file',
            field=models.FileField(blank=True, default='', null=True, upload_to='post_videos'),
        ),
    ]
